# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(choices=[('T', 'TRUE'), ('F', 'FALSE')], default='', max_length=5),
        ),
    ]
